# Generated by Django 2.1.1 on 2018-09-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
