# Generated by Django 2.1.1 on 2018-09-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180925_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pdate',
            field=models.DateTimeField(),
        ),
    ]
